chore: edit yml check gate

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -26,10 +26,23 @@ jobs:
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         # Fail the job if the Quality Gate status is not PASSED
+      # - name: Fail Job if Quality Gate Failed
+      #   if: steps.sonarqube-quality-gate-check.outputs.quality-gate-status != 'PASSED'
+      #   run: exit 1
+
+      # - name: Show SonarQube Quality Gate Status
+      #   run: echo "The Quality Gate status is ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}"
+    
+      # Debugging step to print all outputs from sonarqube-quality-gate-check
+      - name: Print Quality Gate Outputs
+        run: |
+          echo "Quality Gate Status: ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}"
+          echo "All Outputs: ${{ toJSON(steps.sonarqube-quality-gate-check.outputs) }}"
+
+      # Fail the job if the Quality Gate status is not PASSED
       - name: Fail Job if Quality Gate Failed
         if: steps.sonarqube-quality-gate-check.outputs.quality-gate-status != 'PASSED'
         run: exit 1
 
       - name: Show SonarQube Quality Gate Status
         run: echo "The Quality Gate status is ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}"
-    
